version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./library.db:/app/library.db
    networks:
      - library-net

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - library-net

networks:
  library-net:
    driver: bridge
