version: "3.9"

services:
  backend:
    build: .
    container_name: library-backend
    ports:
      - "8080:8080"
    volumes:
      - ./database.db:/root/database.db
    networks:
      - library-net

  frontend:
    image: nginx:alpine
    container_name: library-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - library-net

networks:
  library-net:
    driver: bridge
